### ISSUE TITLE
RDR2 shaders set wrong color space on most textures

### ISSUE THREAD

**Issue by Andicraft** [ultrahacx/Sollumz-RDR#9]
Importing a new model exported from CodeX, most textures are marked as sRGB, causing shading issues:

![image](https://github.com/ultrahacx/Sollumz-RDR/assets/162950/05148b90-c1d8-4a8a-9e36-9a1bc9464cf2)

For accurate rendering, any texture that isn't a `diffusetex` (or other color textures) should be set to Non-Color by default:

![image](https://github.com/ultrahacx/Sollumz-RDR/assets/162950/14532cf4-2a5d-4052-9fa0-9b64c4ff4249)

Right now I have to change these manually on a new import.

**Comment by ultrahacx** [comment]
Resolved with https://github.com/ultrahacx/Sollumz-RDR/pull/10
